### PR TITLE
feat(deps): add support for react 18

### LINKED ISSUE #293: Support react v18
Everything that need to be done in order to support react v18 will be tracked in this issue. You can also have a look at the [React v18 milestone](https://github.com/react-forked/dnd/milestone/2).

We are in the early stage of the investigation, so the list is not yet exhaustive. New issue will be added as we discover them.

**Must have**

- [x] https://github.com/react-forked/dnd/issues/319
- [x] https://github.com/react-forked/dnd/issues/318
- [x] https://github.com/react-forked/dnd/issues/320
- [x] https://github.com/react-forked/dnd/issues/317

**Nice to have**

- [ ] https://github.com/react-forked/dnd/issues/393

### PR DESCRIPTION
**Pull request by 100terres**
fix #293

### CODE REVIEW

**Comment by imekachi** [comment]
Hi @100terres, thank you for working on this and keeping this package alive.
I think there are lots of people waiting for this and some might want to help.
Could you provide a checklist of what needs to be done just in case someone wants to help with this?

**Comment by oravecz** [comment]
wtf would you fork to add React 18 dependency and not publish the package? Some problem with the code running under React 18?

**Comment by 100terres** [comment]
@imekachi @oravecz we might be able to release a beta version this weekend. I'll keep you posted.

**Comment by oravecz** [comment]
Re-read my comment. Apologize for the wording. Thanks for the release.

**Comment by 100terres** [comment]
@oravecz 

> Some problem with the code running under React 18?

Exacly! React 18 brought a couple of breaking changes and it was not an easy fix. Also some of our depedencies needed to be upgraded and in the case of enzyme we needed to completly drop it and use something else. There had been a lot of investigations and code changes.

**Comment by 100terres** [comment]
Beta version released!

https://github.com/react-forked/dnd/releases/tag/v15.0.0-beta.0

**Pull request merged**
